### PR TITLE
Random Workout UI

### LINKED ISSUE #2: Implement random workout endpoint
To Do (within this To Do):
- write a specification for how the data returned will be formatted
- implement api endpoint at `/workouts/random`
- use a fake set of exercises for now (maybe an array or something), before we implement the actual db

### PR DESCRIPTION
**Pull request by daiyi**
This is the feature branch for showing a random workout (: 

random workout preview

Work in progress. 

TODO for @daiyi:
- [x] make the exercise and workout components
- [x] make them better

### CODE REVIEW

**Comment by daiyi** [comment]
The UI side is done, using mocked data, so I'll merge this and @meimeisuns when you start working on the backend portion you can go ahead and replace the mocked API endpoint (:

**Comment by meimeisuns** [comment]
so I just wrote a trivial API that remixes our lil list of fake exercises, but I still can't do `make web-dev` for some reason :¥

**Comment by daiyi** [comment]
you should comment on the issue instead :D just to keep a bit more organisation: #2 

I'll take a look at the web build, hmmmm

**Comment by daiyi** [comment]
OK I found the reason, it's because I forgot to write down the step to install the web dependencies /packages :'D I added it to the readme. https://github.com/sunmoyed/growus/commit/5bade4e590ac2fb9641ef467bcd7a64438953704

**Pull request merged**
